#!/bin/sh


export XDG_RUNTIME_DIR=/run/user/0
mkdir -p "$XDG_RUNTIME_DIR"
chmod 0700 "$XDG_RUNTIME_DIR"

export HOME=/root
export PATH=/usr/bin:/bin:/usr/sbin:/sbin


if [ -x /etc/init.d/network ]; then
    echo "[GUI] Starting network..."
    /etc/init.d/network start
fi

WESTON_BIN=/usr/bin/weston
LOGFILE=/var/log/weston.log

# check if weston exists i hate ts
if [ ! -x "$WESTON_BIN" ]; then
    echo "[GUI] weston not found -> staying in TTY mode"
    exit 0
fi

# logs
mkdir -p /var/log

# try DRM backend first
echo "[GUI] attempting to start weston with DRM backend..."
$WESTON_BIN --backend=drm --shell=kiosk-shell.so --log="$LOGFILE" 2>&1 &
WESTON_PID=$!
sleep 2


# check if weston started
if kill -0 $WESTON_PID 2>/dev/null; then
    echo "[GUI] weston started successfully (PID $WESTON_PID)"
    exit 0
fi

# DRM failed ->  headless for quemu/testing
echo "[GUI] DRM backend failed -> trying headless..."
$WESTON_BIN --backend=headless --shell=kiosk-shell.so --log="$LOGFILE" 2>&1 &
WESTON_PID=$!
sleep 2

if kill -0 $WESTON_PID 2>/dev/null; then
    echo "[GUI] weston (headless) started (PID $WESTON_PID)"
    exit 0
fi

echo "[GUI]aAll backends failed -> check $LOGFILE"
exit 1
